### ISSUE TITLE
Multiple proxy

### ISSUE THREAD

**Issue by hokoo** [sleepm/wp-proxy#1]
What about to store a several sets of proxy and allow to select active one?

**Comment by sleepm** [comment]
If you want to change the proxy quickly, I will consider..

**Comment by john-yyy** [comment]
![image](https://user-images.githubusercontent.com/56463310/117536252-93d21380-b02c-11eb-9fec-4722c72c7919.png)
As shown in the picture above, I used the plug-in, but when I used curl to request s3.amazonaws.com, it still prompted
 ‘Failed connect to s3.amazonaws.com:443; Connection refused’
 
ps : my proxy server is working normally
thanks.

**Comment by sleepm** [comment]
it works with wp_remote_get or wp_remote_post, you can check you proxy server log

> ![image](https://user-images.githubusercontent.com/56463310/117536252-93d21380-b02c-11eb-9fec-4722c72c7919.png)
> As shown in the picture above, I used the plug-in, but when I used curl to request s3.amazonaws.com, it still prompted
> ‘Failed connect to s3.amazonaws.com:443; Connection refused’
> 
> ps : my proxy server is working normally
> thanks.

**Comment by john-yyy** [comment]
There is no corresponding record in the proxy server log.
I tried to manually add a proxy to each curl request, and the log record was generated.
So it feels like, I used the plug-in, but it didn't work.

Last, thank you very much for your reply. :)

**Comment by sleepm** [comment]
wordpress builtin function wp_remote_get() use a filter 'pre_http_send_through_proxy'
this plugin is hook in 'pre_http_send_through_proxy' to use proxy,
so if you use php curl, this plugin will not work...
i'm glad to reply any issue, you're welcome

**Comment by john-yyy** [comment]
Ok, I see.
Thanks! :) :)
















At 2021-05-11 12:18:38, "王登辉" ***@***.***> wrote:

wordpress builtin function wp_remote_get() use a filter 'pre_http_send_through_proxy'
this plugin is hook in 'pre_http_send_through_proxy' to use proxy,
so if you use php curl, this plugin will not work...
i'm glad to reply any issue, you're welcome
