### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RuGaRR** [sleepm/wp-proxy#2]
I am struggling to get this plugin to work.

I tested it by creating my own small plugin that connects to ipchicken.com, scrapes my IP address and outputs it on my page.

If I set the proxy manually in wp-config.php it works fine and the proxy IP is output... but if I set the proxy using this wp-proxy plugin, it makes no difference and my regular IP address is output.

I have entered the domain *.ipchicken.com in the settings.

Any idea why it isn't working?

**Comment by sleepm** [comment]
😃 yes i did it before
*.example.com != example.com

**Comment by sleepm** [comment]
you can try wp-proxy 1.3.9 with global mode

**Comment by RuGaRR** [comment]
Thanks a lot, I got it working! Can you please elaborate on what the new "global mode" setting does?

**Comment by sleepm** [comment]
all the traffic will through the proxy
